[database]
host = "localhost"
port = 27017
database = "taskswap_db"
username = ""
password = ""

[jwt]
secret = "your_super_secret_jwt_key_change_this_in_production"
expiration_seconds = 86400