[package]
org = "taskswap"
name = "backend"
version = "0.1.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.4.1"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.7.0"

[[dependency]]
org = "ballerina"
name = "io"
version = "1.5.0"

[[dependency]]
org = "ballerina"
name = "file"
version = "1.8.1"